# Header Menu
menu:
  Home: /
  Pesquisas: /pesquisas/
#  Projetos: /projects/
  Blog: /archives/ # can set archive-dir in root config to custom value
#  Serviços: /services/
#  Treinamentos: /trainning/
  Contato: /contact/
  Sobre: /about/

rss: /atom.xml

# Content
excerpt_link: Leia mais
fancybox: true # whether or not to load the fancybox library

# Integrations
disqus_shortname: mnestatisticaconsultoria
google_analytics: UA-72688801-1
swiftype_install_key:

# Social
social:
  github: https://github.com/marcionicolau
  twitter: https://twitter.com/mnestatistica
  facebook: https://www.facebook.com/MNConsultoriaEstatistica
  rss: atom.xml
  linkedin: https://linkedin.com/in/marcionicolau
  youtube: https://www.youtube.com/channel/UCoBNPB5TzcgRXkVphfKZHAg

# Miscellaneous
color_scheme: red   # options: blue, gray, green, orange, red, turquoise
favicon: /favicon.ico # path from root of hexo site
twitter_widget_id: "689487724848484352" # as a string, from https://twitter.com/settings/widgets
twitter_username: mnestatistica # twitter username without the @
default_author: MN Estatistica

about: MN Estatística é uma consultoria estabelecida em Passo Fundo, Rio Grande do Sul. <br><br> MN Estatística foi criada em 2015, e seu foco principal é auxiliar os clientes a conhecerem melhor os seus segmentos com base em informações obtidas em pesquisas desenvolvidas a partir de metodologias científicas inovadoras.
phone: (54) 99178-9056
email: contato@mnestatistica.com
address_1: Tranquilo Grazziotin, 297
address_2: Cidade Nova
address_3: Passo Fundo, Rio Grande do Sul
skype: marcio.nicolau
lat: -28.2391886
long: -52.4222794
