# Header Menu
menu:
  Home: /
  Projetos: /projects/
  Blog: /archives/ # can set archive-dir in root config to custom value
  Contato: /contact/
  Sobre: /about/

rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true # whether or not to load the fancybox library

# Integrations
disqus_shortname:
google_analytics:
swiftype_install_key:

# Social
social:
  github: https://github.com/marcionicolau
  twitter: https://twitter.com/marcionicolau
  facebook: https://www.facebook.com/MNConsultoriaEstatistica
  rss: atom.xml
  linkedin: https://linkedin.com/in/marcionicolau
  stackoverflow: http://stackoverflow.com/users/2480493/patrick-steadman

# Miscellaneous
color_scheme: red   # options: blue, gray, green, orange, red, turquoise
favicon: /favicon.ico # path from root of hexo site
twitter_widget_id: "689282980431409156" # as a string, from https://twitter.com/settings/widgets
twitter_username: marcionicolau # twitter username without the @
default_author: MN Estatistica

about: Computer Lab is a software development and marketing company based in Brooklyn, New York. <br><br> Computer Lab was founded in 2015, and is focused on so on and so forth.
phone: (54) 9178-9056
email: mnconsultoriaestatistica@gmail.com
address_1: Tranquilo Grazziotin, 297
address_2: Cidade Nova
address_3: Passo Fundo, Rio Grande do Sul
skype: marcio.nicolau
lat: -28.2395097
long: -52.4244301
